import Notifier from '../notifications/Notifier';
import NotificationOption from '../notifications/NotificationOption';
import Objective from './Objective';

export default class Goal {
    private _name: KnockoutObservable<string>;
    public objectives: KnockoutObservableArray<Objective> = ko.observableArray([]);

    public uuid: string;

    constructor(
        name: string = 'New Goal',
    ) {
        this._name = ko.observable(name);

        this.uuid = crypto.randomUUID?.() ?? // randomUUID is not available in insecure contexts or older browsers
            Array.prototype.slice.apply(crypto.getRandomValues(new Uint8Array(16))) // use getRandomValues to generate 16 bytes
                .map((i: number) => (`0${i.toString(16)}`).slice(-2)).join('') // turn the bytes into their hexadecimal representation
                .replace(/^(.{8})(.{4})(.{4})(.{4})(.+)$/, '$1-$2-$3-$4-$5'); // format like a UUID generated by randomUUID
    }

    createObjective() {
        const objective = new Objective();
        this.objectives.push(objective);
        App.game.goalTracker.selectedObjective(objective);
        $('#goalTrackerObjectiveModal').modal('show');
    }

    async deleteObjective(objective: Objective) {
        if (await Notifier.confirm({
            title: 'Delete objective',
            message: `Are you sure you want to delete "${objective.name}"?`,
            type: NotificationOption.danger,
            confirm: 'Delete',
        })) {
            this.objectives.remove(objective);
        }
    }

    get name(): string {
        return this._name();
    }

    set name(value: string) {
        this._name(value);
    }

    toJSON(): Record<string, any> {
        return {
            name: this.name,
            objectives: this.objectives().filter(obj => obj.type !== undefined).map(obj => obj.toJSON()),
        };
    }

    fromJSON(json: Record<string, any>): void {
        this.name = json.name;

        const objectives = [];

        json.objectives?.forEach((objectiveJson) => {
            const objective = new Objective();
            objective.fromJSON(objectiveJson);
            objectives.push(objective);
        });

        this.objectives(objectives);
    }
}
